// Card text, and the presentation data that rules.js deliberately doesn't carry.
//
// The rules text is GENERATED by running each card's effect function against
// a recording probe and rendering what it called. Hand-written card text on
// 55 cards would drift from the code the first time a value changed - this
// cannot. The only hand-written parts are the conditions, which live in
// CONDITIONS below because a probe can't see which branch was taken.

var CHARACTER_ART = {
  dean_kean: {
    portrait: "portrait_deankean.png", sprite: "char_deankean.png",
    blurb: "Power. He misses more than the others and hurts more when he connects."
  },
  speedster: {
    portrait: "portrait_speedster.png", sprite: "char_speedster.png",
    blurb: "Small ball. Walks, steals and sacrifices — he manufactures runs without hits."
  },
  all_purpose: {
    portrait: "portrait_allpurpose.png", sprite: "char_allpurpose.png",
    blurb: "Value. Fewer weaknesses, fewer spikes, and the deepest card draw."
  }
};

for (var cid in CHARACTER_ART) {
  if (CHARACTERS[cid]) {
    CHARACTERS[cid].portrait = CHARACTER_ART[cid].portrait;
    CHARACTERS[cid].sprite = CHARACTER_ART[cid].sprite;
    CHARACTERS[cid].blurb = CHARACTER_ART[cid].blurb;
  }
}

// cards whose effect depends on board state - the probe sees one branch only
var CONDITIONS = {
  clutch:      { o: "Contact 1. Contact 2 with a runner on third.",
                 d: "Stuff 1. Stuff 2 with two outs." },
  second_deck: { o: "Power 1. Power 4 at two strikes.",
                 d: "Stuff 1. Stuff 3 with two outs." },
  captain:     { o: "Contact 1. Contact 2 with a runner in scoring position.",
                 d: "Stuff 1. Glove 1." }
};

var PHRASES = {
  contact: function (n) { return n < 0 ? '<span class="bad">Contact ' + n + ".</span>" : "Contact " + n + "."; },
  power:   function (n) { return "Power " + n + "."; },
  stuff:   function (n) { return "Stuff " + n + "."; },
  glove:   function (n) { return n < 0 ? '<span class="bad">Glove ' + n + ".</span>" : "Glove " + n + "."; },
  draw:    function (n) { return "Draw " + n + "."; },
  steal:   function ()  { return "Steal a base."; },
  pickoff: function ()  { return "Pick off a runner in scoring position — that's an out."; },
  hold:    function ()  { return "Hold the runner — catches him if he steals."; },
  tagUp:   function ()  { return '<span class="kw">Tag Up</span> — a ball in play scores your runner from third.'; },
  dp:      function ()  { return '<span class="kw">Double Play</span> — a ball in play doubles him off.'; },
  ball:    function ()  { return "Take a ball."; },
  giveBall:function ()  { return '<span class="bad">He takes a ball.</span>'; },
  strike:  function ()  { return '<span class="bad">Take a strike.</span>'; },
  foul:    function ()  { return "Foul it off — no strike at two."; },
  advance: function (n) { return "All runners advance " + n + "."; },
  stamina: function (n) { return '<span class="good">+' + n + " stamina.</span>"; },
  // the same engine call means opposite things depending on the side, so
  // these two need to know which half they're being read in
  resetSettle: function (n, side) {
    return side === "o" ? '<span class="good">Step Out</span> — his groove resets.'
                        : '<span class="bad">You lose your groove.</span>';
  },
  settleEarly: function (n, side) {
    return side === "o" ? '<span class="bad">He digs in</span> — +1 to his groove.'
                        : '<span class="good">Settle in</span> — +1 to yours.';
  },
  chokeUp:     function () { return "Your hit this turn is a single."; },
  coolOff:     function () { return '<span class="good">Cool him off</span> — he loses a step of his groove.'; }
};

// A stand-in that records what a card's effect function calls, instead of
// actually doing it.
function makeProbe() {
  var calls = [];
  var probe = {
    state: { bases: [false, false, false], outs: 0, strikes: 0, balls: 0, forceFoul: false },
    contact: function (n) { calls.push(["contact", n]); },
    power:   function (n) { calls.push(["power", n]); },
    stuff:   function (n) { calls.push(["stuff", n]); },
    glove:   function (n) { calls.push(["glove", n]); },
    draw:    function (n) { calls.push(["draw", n]); },
    steal:   function ()  { calls.push(["steal"]); return true; },
    pickoff: function ()  { calls.push(["pickoff"]); return true; },
    hold:    function ()  { calls.push(["hold"]); },
    tagUp:   function ()  { calls.push(["tagUp"]); },
    armDoublePlay: function () { calls.push(["dp"]); },
    takeBall: function () { calls.push(["ball"]); },
    giveBall: function () { calls.push(["giveBall"]); },
    takeStrike: function () { calls.push(["strike"]); },
    addStrike: function () { calls.push(["strike"]); },
    advance: function (n) { calls.push(["advance", n]); },
    scoreRun: function () { calls.push(["run"]); },
    gainStamina: function (n) { calls.push(["stamina", n]); },
    resetSettle: function () { calls.push(["resetSettle"]); },
    settleEarly: function () { calls.push(["settleEarly"]); },
    chokeUp:     function () { calls.push(["chokeUp"]); },
    coolOff:     function () { calls.push(["coolOff"]); },
    recomputeSettle: function () {}
  };
  probe.calls = calls;
  return probe;
}

function describeSide(cardId, side) {
  if (CONDITIONS[cardId] && CONDITIONS[cardId][side]) return CONDITIONS[cardId][side];

  var card = CARDS[cardId];
  if (!card) return "";
  if (card.unplayable) return "Unplayable. Clogs your deck.";

  var probe = makeProbe();
  var before = probe.state.forceFoul;
  try { card[side](probe); } catch (e) { return ""; }

  var parts = [];
  if (probe.state.forceFoul !== before) parts.push(PHRASES.foul());

  // merge repeated calls so "Steal. Steal." reads as "Steal twice."
  var merged = {};
  probe.calls.forEach(function (c) {
    var key = c[0];
    if (merged[key] === undefined) merged[key] = { n: c[1] || 0, count: 1 };
    else { merged[key].n += (c[1] || 0); merged[key].count++; }
  });

  ["contact", "power", "stuff", "glove", "advance", "steal", "pickoff",
   "ball", "giveBall", "strike", "tagUp", "dp", "hold", "chokeUp", "coolOff",
   "resetSettle", "settleEarly", "draw", "stamina"].forEach(function (key) {
    var m = merged[key];
    if (!m) return;
    if (key === "steal" && m.count > 1) { parts.push("Steal " + m.count + " bases."); return; }
    if (key === "pickoff" && m.count > 1) { parts.push("Pick off " + m.count + " runners — two outs."); return; }
    if (key === "ball" && m.count > 1) { parts.push("Take " + m.count + " balls."); return; }
    parts.push(PHRASES[key](m.n, side));
  });

  return parts.join(" ");
}
